# Generated by Django 3.1.4 on 2021-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0021_threatagentquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatagentquestion',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
