# Generated by Django 3.1.4 on 2021-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0023_reply_tareplies_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=500),
        ),
    ]
