# Generated by Django 3.1.4 on 2021-04-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0024_auto_20210326_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAgentAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100, null=True)),
                ('attribute_value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAgentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('common_actions', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TACategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threatagentattribute')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threatagentcategory')),
            ],
        ),
    ]
