# Generated by Django 3.1.4 on 2021-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0025_tacategoryattribute_threatagentattribute_threatagentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
