# Generated by Django 3.1.4 on 2021-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0026_auto_20210430_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatagentattribute',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='threatagentattribute',
            name='score',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
