# Generated by Django 3.1.2 on 2021-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0029_auto_20210610_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
