# Generated by Django 3.1.2 on 2021-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0030_reply_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatagentquestion',
            name='Qid',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
