# Generated by Django 3.1.2 on 2021-09-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0031_threatagentquestion_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAgentRiskScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField()),
                ('size', models.IntegerField()),
                ('motive', models.IntegerField()),
                ('opportunity', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm')),
            ],
        ),
    ]
