# Generated by Django 3.1.2 on 2021-09-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0032_threatagentriskscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrideImpactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialdamage', models.IntegerField()),
                ('reputationdamage', models.IntegerField()),
                ('noncompliance', models.IntegerField()),
                ('privacyviolation', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm')),
                ('stride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.stride')),
            ],
        ),
    ]
