# Generated by Django 3.1.2 on 2021-09-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0033_strideimpactrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm'),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='financialdamage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='noncompliance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='privacyviolation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='reputationdamage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='stride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.stride'),
        ),
    ]
