# Generated by Django 3.1.2 on 2021-09-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0034_auto_20210927_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACM_ThreatAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threatagentcategory')),
            ],
        ),
    ]
