# Generated by Django 3.1.2 on 2021-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0035_macm_threatagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatagentriskscores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='threatagentriskscores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
