# Generated by Django 3.1.2 on 2021-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0036_auto_20210929_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='strideimpactrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='strideimpactrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
