# Generated by Django 3.1.2 on 2021-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0037_auto_20210930_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='PostCondition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='PreCondition',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
